# Generated by Django 5.0.1 on 2024-02-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_service',
        ),
    ]
